version: "3.9"
services:
  backend:
    env_file:
      - ../.env.backend
      - ../.env.stripe
      - ../.env.metrc
      - ../.env.scheduler
    ports:
      - "8000:8000"
    volumes:
      - ../backend/app:/app/app:ro
  frontend:
    build:
      args:
        # For local dev, you can call API directly
        VITE_API_BASE_URL: http://localhost:8000
    ports:
      - "8080:80"
