FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY app /app/app
COPY openapi /app/openapi
COPY .env.example /app/.env.example

EXPOSE 8000

CMD ["flask", "--app", "app", "run", "--host=0.0.0.0", "--port", "8000"]
